services:
  postgres:
    image: postgres:16
    container_name: cubos-movies
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies_db
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - pg_movies_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d movies_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_movies_data: